# Swell Categorization Scheme
# (auto-written by /api/tuner/save; edit in /tuner or this file)

[[band]]
period_upper_bound = 5.9
FLAT    = "always"
WEAK    = "never"
FUN     = "never"
SOLID   = "never"
FIRING  = "never"
HECTIC  = "never"
MONSTRO = "never"

[[band]]
period_upper_bound = 7.5
FLAT    = 2.5
WEAK    = 5.0
FUN     = 8.0
SOLID   = "never"
FIRING  = "never"
HECTIC  = ">=8"
MONSTRO = "never"

[[band]]
period_upper_bound = 9.5
FLAT    = 2.0
WEAK    = 4.0
FUN     = 7.5
SOLID   = 12.0
FIRING  = "never"
HECTIC  = ">=12"
MONSTRO = "never"

[[band]]
period_upper_bound = 12.5
FLAT    = 1.5
WEAK    = 2.0
FUN     = 4.5
SOLID   = 7.5
FIRING  = 9.5
HECTIC  = ">=9.5"
MONSTRO = "never"

[[band]]
period_upper_bound = 15.5
FLAT    = 2.0
WEAK    = 3.0
FUN     = 4.0
SOLID   = 6.0
FIRING  = 14.0
HECTIC  = ">=14"
MONSTRO = "never"

[[band]]
period_upper_bound = 17.5
FLAT    = 1.0
WEAK    = "never"
FUN     = 3.0
SOLID   = 5.0
FIRING  = 10.0
HECTIC  = "never"
MONSTRO = ">=10"

[[band]]
period_upper_bound = "inf"
FLAT    = 1.0
WEAK    = "never"
FUN     = 3.0
SOLID   = 4.0
FIRING  = 8.0
HECTIC  = "never"
MONSTRO = ">=8"

